/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "DevFlow": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "DevopsDutyCloud": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Games": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "LiveDocs": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "NihaRana": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Portfolio": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Reddipod": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Todo": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
